# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: incredibl.us
email: tammo@incredibl.us
description: > # this means to ignore newlines until "baseurl:"
  Python developers focused on quality code. We write code, we fix code.
  Need to have your code refactored? We are here to help. Something in your
  code not working? Let us know and we fix it. Do you need to get data of
  webpages? We can help.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.incredibl.us" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  incrediblus

# Build settings
markdown: kramdown
